import type { Metadata } from "next";
import "./globals.css";
import { firaSans } from "./ui/fonts";
import StoreProvider from "./StoreProvider";

export const metadata: Metadata = {
  title: "DesigualLab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={firaSans.className}>
        <StoreProvider>
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
