import { IndicatorGroup } from "./definitions";

export const indicatorsList: IndicatorGroup[] = [
  {
    id: 1,
    subject: "Saúde",
    indicators: [
      {
        indicatorId: 1,
        title: "Idade Média ao Morrer",
        subtitle: "Idade Média ao Morrer, por distrito",
        mapPath: "35MjM/2/",
        histogramPath: "j6Yvx/1/",
        tablePath: "buIGU/1/",
        odsPath: "SDG-3.svg",
        formula: "Média da idade (em anos) das pessoas que morreram",
        remarks: "",
        year: 2021,
        source: "Secretaria Municipal de Saúde",
        bestDistrict: "Parreão",
        bestValue: 77.1,
        worseDistrict: "Novo Mondubim",
        worseValue: 56,
        median: 67.2,
        mean: 67.1,
        asymmetry: 1.06,
      },
      {
        indicatorId: 2,
        title: "Gravidez na Adolescência",
        subtitle: "Gravidez na Adolescência, por distrito",
        mapPath: "HfGni/2/",
        histogramPath: "gZABq/6/",
        tablePath: "wVxkG/3/",
        odsPath: "SDG-3.svg",
        formula: "Nascidos vivos de adolescentes ÷ número de nascidos vivos",
        remarks:
          "Consideram-se adolescentes para este cálculo mulheres com até 19 anos",
        year: 2023,
        source: "Secretaria Municipal de Saúde",
        bestDistrict: "De Lourdes",
        bestValue: 0,
        worseDistrict: "Novo Mondubim",
        worseValue: 28.6,
        median: 10.6,
        mean: 10.7,
        asymmetry: -7.13,
      },
      {
        indicatorId: 3,
        title: "Mortalidade Materna",
        subtitle:
          "Coeficiente de mortalidade por causas maternas, para cada 1000 nascidos vivos de mães residentes no distrito",
        mapPath: "G99Dk/1/",
        histogramPath: "MtW9E/1/",
        tablePath: "meQIF/1/",
        odsPath: "SDG-3.svg",
        formula:
          "Total de óbitos por causas maternas ÷ Total de nascidos vivos x 1000",
        remarks:
          'Para efeitos do cálculo foram utilizados os totais anuais. Número de óbitos considerados como maternos, segundo o local de residência da falecida. Foram selecionados os seguintes óbitos femininos, independentemente da idade, causados por: 1. Afecções do Capítulo XV da CID-10 "Gravidez, Parto e Puerpério", códigos O00-O99, com exceção das mortes fora do período do puerpério de 42 dias',
        year: 2021,
        source: "Secretaria Municipal de Saúde",
        bestDistrict: 97,
        bestValue: 0,
        worseDistrict: "Damas",
        worseValue: 8.5,
        median: 0,
        mean: 0.71,
        asymmetry: 100,
      },
      {
        indicatorId: 4,
        title: "Mortalidade Infantil",
        subtitle: "Taxa de mortalidade em menores de 1 ano",
        mapPath: "dsety/1/",
        histogramPath: "VJIkU/1/",
        tablePath: "BRyLI/1/",
        odsPath: "SDG-3.svg",
        formula:
          "Total de óbitos de menores de 1 ano ÷ Total de nascidos vivos ÷ 1000",
        remarks: "Para efeitos do cálculo foram utilizados os totais anuais",
        year: 2021,
        source: "Secretaria Municipal de Saúde",
        bestDistrict: 24,
        bestValue: 0,
        worseDistrict: "Jardim Iracema",
        worseValue: 39,
        median: 10.2,
        mean: 10.6,
        asymmetry: 3.05,
      },
      {
        indicatorId: 5,
        title: "Mortalidade Neonatal",
        subtitle: "Taxa de mortalidade em menores de 28 dias",
        mapPath: "TDK3C/1/",
        histogramPath: "SnSRu/1/",
        tablePath: "L2cmo/1/",
        odsPath: "SDG-3.svg",
        formula:
          "Total de óbitos de menores de 28 dias ÷ total de nascidos vivos x 1000",
        remarks: "Para efeitos do cálculo foram utilizados os totais anuais",
        year: 2021,
        source: "Secretaria Municipal de Saúde",
        bestDistrict: 43,
        bestValue: 0,
        worseDistrict: "De Lourdes",
        worseValue: 37,
        median: 5.37,
        mean: 6.7,
        asymmetry: 23.5,
      },
      {
        indicatorId: 6,
        title: "Mortalidade por Doenças Crônicas Não Transmissíveis",
        subtitle:
          "Número de óbitos (entre 30 e 69 anos) por DCNT registrados nos códigos CID-10 – I00-I99; C00-C97; J30-J98, exceto J36; E10-E14 – em determinado ano e local dividido pela população residente multiplicado por 100.000",
        mapPath: "c7l1j/1/",
        histogramPath: "hPMm1/2/",
        tablePath: "sViRa/1/",
        odsPath: "SDG-3.svg",
        formula:
          "Número de óbitos por Doenças Crônicas Não Transmissíveis ÷ população residente x 100.000",
        remarks:
          "Para efeitos do cálculo foram consideradas doenças do aparelho circulatório, tumores malignos, diabetes mellitus e doenças crônicas respiratórias.",
        year: 2021,
        source: "Secretaria Municipal de Saúde",
        bestDistrict: 3,
        bestValue: 0,
        worseDistrict: "Pedras",
        worseValue: 422,
        median: 124,
        mean: 126,
        asymmetry: 2,
      },
    ],
  },
  {
    id: 2,
    subject: "População",
    indicators: [
      {
        indicatorId: 3,
        title: "Gravidez na Adolescência",
        subtitle: "Gravidez na Adolescência, por distrito",
        mapPath: "https://datawrapper.dwcdn.net/HfGni/2/",
        histogramPath: "https://datawrapper.dwcdn.net/gZABq/6/",
        tablePath: "https://datawrapper.dwcdn.net/wVxkG/3/",
        odsPath: "SDG-3.svg",
        formula:
          "Nascidos vivos de adolescentes * dividido pelo número de nascidos vivos",
        remarks:
          "Consideram-se adolescentes para este cálculo mulheres com até 19 anos",
        year: 2023,
        source: "Secretaria Municipal de Saúde",
        bestDistrict: "De Lourdes",
        bestValue: 0,
        worseDistrict: "Novo Mondubim",
        worseValue: 28.6,
        median: 10.6,
        mean: 10.7,
        asymmetry: -7.13,
      },
    ],
  },
];

export const subjectsList = [
  "Saúde",
  "População",
  "Habitação",
  "Educação",
  "Esporte e lazer",
  "Mobilidade urbana",
  "Segurança",
  "Meio ambiente",
  "Saneamento básico"
];

export const InitialMenu = {
  desigualLab: true,
  team: false,
  who: false,
  partners: false,
  assignments: false,
  projects: false,
  publications: false,
  schedule: false,
  press: false,
};
